In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import sys
%matplotlib inline

In [2]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [3]:
## Create a dataframe
df = pd.DataFrame({
    'color' : ['red','blue','green','red','blue']
})

In [4]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\vikas\OneDrive\Desktop\Data-Analytics\DA\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [5]:
lbl_encoder.transform([['red']])

c:\Users\vikas\OneDrive\Desktop\Data-Analytics\DA\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

## Ordinal Encoding
- Ordinal encoding is a type of encoding where each unique category value is assigned an integer value.

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df = pd.DataFrame({
    'size' : ['small','medium','large','medium','small','large']
})

In [9]:
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [11]:
OE = OrdinalEncoder(categories=[['small','medium','large']])
OE.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [12]:
OE.transform([['small']])

c:\Users\vikas\OneDrive\Desktop\Data-Analytics\DA\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [13]:
print("The End")

The End
